Ext.define('MyApp.model.store.auditoria.AuditoriaStore', {
    extend: 'Ext.data.Model',
    fields: [
    	{name: 'id',        		type: 'int'},
        {name: 'idC',               type: 'int'},
        {name: 'idP',               type: 'int'},
        {name: 'idD'               },
        {name: 'idIP',              type: 'int'},
        {name: 'idID',              type: 'int'},
        {name: 'idPA'              },
        {name: 'idA',               type: 'int'},
        {name: 'idR'               },
        {name: 'idAR',              type: 'int'},
        {name: 'idAR2',             type: 'int'},
        {name: 'dpto',              type: 'int'},
    	{name: 'codigo',    		type: 'string'},
        {name: 'codigoC',           type: 'string'},
    	{name: 'ente',      		type: 'string'},
        {name: 'division',          type: 'string'},
        {name: 'nombreE',           type: 'string'},
        {name: 'nombreT',           type: 'string'},
        {name: 'nombre',            type: 'string'},
        {name: 'auditoria',         type: 'string'},
        {name: 'ente_nombre',       type: 'string'},
        {name: 'tipo_auditoria',    type: 'string'},
        {name: 'tipo',              type: 'string'},
    	{name: 'objetivo_general',  type: 'string'},
        {name: 'enfoque', 			type: 'string'},
        {name: 'alcance',    		type: 'string'},
    	{name: 'fecha',      		type: 'string'},
        {name: 'fechaB',            type: 'string'},
        {name: 'fecha_aprobacion',  type: 'string'},
        {name: 'origen_auditoria',  type: 'string'},
        {name: 'dias_programa',   	type: 'string'},
    	{name: 'dias_informe',      type: 'string'},
        {name: 'fechaC',            type: 'string'},
        {name: 'dias',              type: 'string'},
        {name: 'diasE',             type: 'string'},
        {name: 'diasP',             type: 'string'},
        {name: 'fechaI',            type: 'string'},
        {name: 'fechaO',            type: 'string'},
        {name: 'fechaF',            type: 'string'},
        {name: 'denunciante',       type: 'string'},
        {name: 'estado',            type: 'string'},
        {name: 'bitacora',          type: 'string'},
        {name: 'oficio_denuncia',   type: 'string'},
        {name: 'solicitante',       type: 'string'},
        {name: 'observacion',       type: 'string'},
        {name: 'oficio_solicitud',  type: 'string'},
        {name: 'estatus',  			type: 'string'},
        {name: 'estatusB',          type: 'string'},
        {name: 'recomendacion',     type: 'int'},
        {name: 'fecha_registro',    type: 'date'},
        {name: 'fecha_recepcion'},
        {name: 'recomendacionPA',   type: 'int'},
        {name: 'fecha_registroPA',  type: 'date'},
        {name: 'fecha_recepcionPA'}
    ]
});