Ext.define('MyApp.model.store.auditoria.ProgramaStore', {
    extend: 'Ext.data.Model',
    idProperty: 'bitacora',
    fields: [
    	{name: 'id',        		type: 'int'},
        {name: 'idA',               type: 'int'},
        {name: 'idC',               type: 'int'},
        {name: 'idP',               type: 'int'},
    	{name: 'codigo',    		type: 'string'},
        {name: 'codigoC',           type: 'string'},        
        {name: 'codigoP',           type: 'string'},
    	{name: 'ente',      		type: 'string'},
        {name: 'nombre',            type: 'string'},
        {name: 'nombreT',           type: 'string'},
        {name: 'descripcion',       type: 'string'},
        {name: 'descripcionPT',     type: 'string'},
        {name: 'ente_nombre',       type: 'string'},
        {name: 'tipo_auditoria',    type: 'string'},
        {name: 'tipo',              type: 'string'},
    	{name: 'objetivo_general',  type: 'string'},
        {name: 'enfoque', 			type: 'string'},
        {name: 'alcance',    		type: 'string'},
    	{name: 'fecha',      		type: 'string'},
        {name: 'fechaP',            type: 'string'},
        {name: 'fechaB',            type: 'string'},
        {name: 'bitacora',          type: 'string'},
        {name: 'origen_auditoria',  type: 'string'},
        {name: 'fecha_aprobacion',	type: 'string'},
    	{name: 'dias_informe',      type: 'string'},        
        {name: 'dias_duracion',     type: 'string'},
        {name: 'fecha_credencial',  type: 'string'},
        {name: 'fecha_instalacion', type: 'string'},
        {name: 'fecha_oficio',      type: 'string'},
        {name: 'observacion',       type: 'string'},
        {name: 'estatus',  			type: 'string'},
        {name:'nombreFuncionario',  type: 'string'},
        {name: 'estatusB',          type: 'string'},
        {name: 'estado',            type: 'string'}
    ]
});